### ISSUE TITLE
add chainmap on conda-forge

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/aiida-core-feedstock#11]
the chainmap dependency is currently available only on bioconda, see
https://anaconda.org/search?q=chainmap

**Comment by ltalirz** [comment]
@astamminger would you mind helping out with this?

**Comment by astamminger** [comment]
@ltalirz can you give me a hint on what this package is actually for? It is used nowhere in the AiiDA code. Is this really just needed by read-the-docs?

**Comment by ltalirz** [comment]
@astamminger Well spotted!

It's not quite true that it is used nowhere in aiida as it is [imported here](https://github.com/aiidateam/aiida_core/blob/aaa8c687bd325bedf1d4aeca479d4ca9a2b96eb4/aiida/common/caching.py#L19) (and this made `verdi quicksetup` fail for me using the conda installation) but

 1. the import is actually not used, even in 0.12.x
 2. the import is gone in 1.0 but the dependency remained

Time to remove another dependency (one of my favourite things to do ;-) )

**Comment by astamminger** [comment]
Ah i see! I only checked out the ``develop`` branch :)

> 1. the import is actually not used, even in 0.12.x

Yes, at least not in the conda-forge builds.

> Time to remove another dependency (one of my favourite things to do ;-) )

:+1:

**Comment by ltalirz** [comment]
> Yes, at least not in the conda-forge builds.

Just to clarify: it *does* break `verdi import` on `aiida-core==0.12.3` installed via conda.

**Comment by astamminger** [comment]
Interesting. I based that assumption on the chainmap docs ([https://bitbucket.org/jeunice/chainmap](url)) where it states the builds used on conda-forge (i.e. ``python==2.7/3.6``) should not need ``chainmap``. Which does not seem to be true for ``python==2.7``.

**Comment by astamminger** [comment]
Since we obviously need ``chainmap`` for ``aiida-core`` versions using ``python==2.7``:
conda-forge/staged-recipes#8218
bioconda/bioconda-recipes#14954

**Comment by ltalirz** [comment]
ah, thanks!

> Since we obviously need chainmap for aiida-core versions using python==2.7

Just to make sure I'm not missing anything here: do you mean it is *actually* needed (if yes, I'd like to understand why) or just because we have this leftover import, which I'm going to remove in aiida-core 0.12.4?

**Comment by ltalirz** [comment]
see https://github.com/aiidateam/aiida_core/pull/2801 and https://github.com/aiidateam/aiida_core/pull/2799

**Comment by astamminger** [comment]
Ah, no you're right (I assumed the imported ``ChainMap`` was really used somewhere in the code)
However, if it is only imported but never used than forget what I said :)

**Comment by astamminger** [comment]
Closing this because the feedstock was just created (https://github.com/conda-forge/chainmap-feedstock)
