### ISSUE TITLE
add extras of aiida-core as additional outputs

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/aiida-core-feedstock#12]
the `environment.yml` did not allow to do this, but in the conda-forge feedstock we can now add extras as "outputs". 

We already have one for installing rabbitmq & postgresql but one should add the  extras defined in the setup.json as well
https://github.com/conda-forge/aiida-core-feedstock/blob/master/recipe/meta.yaml#L81 (edited)

**Comment by astamminger** [comment]
Finally found some time to have a look at the extras dependencies. Here's what I got:

|extra|deps|conda-forge-alias|available|in progress|missing
|---|---|---|---|---|---|
**ssh-kerberos** | gssapi | python-gssapi | x |  |  |
|  | pyasn1 | pyasn1 | x |  |  |
|**rest**  | flask-cors | flask-cors | x |  |  |
|  | flask-restful | flask-restful | x |  |  |
|  | flask | flask | x |  |  |
|  | pyparsing | pyparsing | x |  |  |
|  | python-memcached | python-memcached | x |  |  |
|  | seekpath | seekpath | x |  |  |
| **docs** | docutils | docutils | x |  |  |
|  | pygments | pygments | x |  |  |
|  | pydata-sphinx-theme | pydata-sphinx-theme | x |  |  |
|  | sphinx | sphinx | x |  |  |
|  | sphinxcontrib-details-directive | sphinxcontrib-details-directive |  | [sphinxcontrib-details-directive](https://github.com/astamminger/staged-recipes/tree/sphinxcontrib-details-directive) |  |
|  | sphinx-panels | sphinx-panels | x |  |  |
|  | sphinx-copybutton | sphinx-copybutton | x |  |  |
|  | sphinx-notfound-page | sphinx-notfound-page |  | [sphinx-notfound-page](https://github.com/astamminger/staged-recipes/tree/sphinx-notfound-page) |  |
|  | sphinxext-rediraffe | sphinxext-rediraffe |  | [sphinxext-rediraffe](https://github.com/astamminger/staged-recipes/tree/sphinxext-rediraffe) |  |
| **atomic_tools**  | PyCifRW | pycifrw | x |  |  |
|  | ase | ase | x |  |  |
|  | pymatgen | pymatgen | x |  |  |
|  | pymysql | pymysql | x |  |  |
|  | seekpath | seekpath | x |  |  |
|  | spglib | spglib | x |  |  |
| **notebook** | jupyter | jupyter | x |  |  |
|  | notebook | notebook | x |  |  |
| **bpython** | bpython | bpython | x |  |  |

Looks actually pretty complete, expected it to be much worse :D Only missing deps are some extensions to sphinx which I already started to add to conda-forge. Before starting to merge them please give me a ping if you would like to be added as package maintainers as well @ltalirz @chrisjsewell 

I did not add the dependencies for the **pre-commit** and **tests** extras to the list as it doesn't make sense (at least to me) to add these as outputs in the conda build. (Who uses conda for development??? Anyway, the dependencies **are** available! The only packages missing seem to be *aiida-homegrown* and are all owned by @chrisjsewell and are available from his personal anaconda repo. Should be fairly easy to transfer them to conda-forge if need)

Cheers

**Comment by ltalirz** [comment]
Hey Andreas, how nice of you to take this on!



> Before starting to merge them please give me a ping if you would like to be added as package maintainers as well @ltalirz @chrisjsewell

I suggest adding @chrisjsewell since I believe those were added by him and he contributed at least to some of them.


 for sphinx-notfound and sphinx-rediraffe and @greschd for 

> I did not add the dependencies for the **pre-commit** and **tests** extras to the list as it doesn't make sense (at least to me) to add these as outputs in the conda build. (Who uses conda for development???

I certainly don't ;-) I think it's fine to start without the `pre-commit` and `tests` extras; as long as the "packages found by inspection" in https://github.com/conda-forge/aiida-core-feedstock/pull/45 are available that's fine.

**Comment by astamminger** [comment]
Hi @chrisjsewell, would that be OK for you? :)

**Comment by chrisjsewell** [comment]
hey yeh sounds good to me thanks. The `docs` extra I don't think is really necessary, since it is only for the internal documentation build

**Comment by chrisjsewell** [comment]
Hey @astamminger sorry forget to reply to the comments in https://github.com/conda-forge/staged-recipes/pull/13996, https://github.com/conda-forge/staged-recipes/pull/13997 😬 
The only thing I was gonna add is that I wanted to mention to @tk0miya and @humitos that their packages have been added to conda-forge.
I had a bit of a "debate" with the conda-forge admins not too long ago, when I found a number of my other packages had been added to conda-forge without my knowledge.
I very much disagree with their refusal to not even suggest contacting maintainers in the recipe PR checklist

**Comment by humitos** [comment]
Hi all! Thanks @chrisjsewell for pinging me here.

I'm taking the opportunity to say that I found a friendly "ping" useful. Honestly, I'm not super involved in the conda ecosystem, but knowing that the extension that I co-maintain will be available as a conda-forge package is good to know.

Also, thanks for taking the time to make this happen and allow conda users to easily install this extension!

**Comment by astamminger** [comment]
> Hey @astamminger sorry forget to reply to the comments in [conda-forge/staged-recipes#13996](https://github.com/conda-forge/staged-recipes/pull/13996), [conda-forge/staged-recipes#13997](https://github.com/conda-forge/staged-recipes/pull/13997) 😬 but all good cheers

No big deal, I could point them to this thread :)

> I had a bit of a "debate" with the conda-forge admins not too long ago, when I found a number of my other packages had been added to conda-forge without my knowledge.
> I very much disagree with their refusal to not even suggest contacting maintainers in the recipe PR checklist

Well, I do not know why you would debate with conda-forge admins about packages being added without your knowledge, IMHO that's how open source works, isn't it? However, I fully agree with you from a netiquette point of view and it also confused me a lot when I added the first package to conda-forge that actually not a single soul got a ping. But I think if they don't have to they just don't do it ;)

@humitos @tk0miya If you guys ever want to be added to the recipe's maintainers list just let me know!

**Comment by chrisjsewell** [comment]
> I fully agree with you from an etiquette point of view

well thats exactly the point

**Comment by ltalirz** [comment]
If there's interest in adding the extras as subpackages together with https://github.com/conda-forge/aiida-core-feedstock/issues/41 now might be a good time

**Comment by ltalirz** [comment]
Was addressed in 07/2022 by a722680c2c48a5198972178e17441564440aa260
