### ISSUE TITLE
Add `run_constrained` field linking aiida-core & services versions

### ISSUE THREAD

**Issue by chrisjsewell** [conda-forge/aiida-core-feedstock#33]
As discussed in https://github.com/aiidateam/aiida-core/pull/4147#issuecomment-638714186,
Conda is really not happy trying to solve the environment for `aiida-core` + `aiida-core.services`.

Maybe a root issue here is that `aiida-core` and `aiida-core.services` are two completely separate packages, when really you want services to act like extra requirements do in setup.py, e.g. `aiida-core[services]`.
Having a quick google, it might be good to add a https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained in the `aiida-core` package, to tie it to the same version of `aiida-core.services` i.e.:

```yaml
requirements:
  run_constrained:
    - aiida-core.services =={{ version }}
```

which would constrain the possibilities for conda environment solving

**Comment by ltalirz** [comment]
Sounds good to me!
