### ISSUE TITLE
Consider restructuring the recipe with the next release

### ISSUE THREAD

**Issue by astamminger** [conda-forge/aiida-core-feedstock#41]
Changing the package type to ``noarch`` showed that choosing identical names for top- and sub-packages can possibly lead to spurious errors in the build process. In particular, the ``noarch: python`` option was not properly propagated to the subpackage during the build process (see PR #37).  (I am not 100% sure if the package naming is really the reason for that behavior but considering the very similar issue discussed [here](https://github.com/conda/conda-build/issues/3702) I think it's likely) 

To avoid this in the future we could maybe use a recipe layout similar to the one used in the [matplotlib recipe](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml) with different names for top- and sub-packages and the top-package only containing very general information while all the specific requirements are moved to the individual sub-packages.

**Comment by ltalirz** [comment]
Thanks for the suggestion @astamminger . What isn't quite clear to me from https://github.com/conda/conda-build/issues/3702 is what "naming the same" is supposed to mean - does it mean "starts with the same string"?

In any case, so far your solution of simply re-specifying the flag in the output package seems to work fine and I would suggest to keep the name for the moment unless we run into issues again.

**Comment by astamminger** [comment]
@ltalirz sorry for the late response! No I think it really means "the names are identical". In the referenced recipe the top-level package name after substitution would be ``jupyterlab-git-server``. However, this name is identical to the sub-package name ``jupyterlab-git-server`` defined in the outputs section. This is exactly what we're doing in the ``aiida-core`` recipe at the moment and 

1. might lead to unforeseen and unpredictable trouble (see the last build)
2. is clearly discouraged, see https://github.com/conda/conda-build/issues/3702#issuecomment-527765431

Regarding your second point. Just to clarify that we are talking about the same thing here. I was not talking about renaming the ``aiida-core`` output package. My suggestion was to rename the top-level package and keep the ``aiida-core`` output package but move the package's build options and requirements from the top-level the corresponding sub-package (i.e. really treat them as individual packages). Anyway, I'm fine with sticking to the current solution but I am not sure if we're using the ``outputs`` in the correct way at the moment.

**Comment by ltalirz** [comment]
Oh, now I see (I overlooked that we also specify `aiida-core` explicitly among the `outputs`).

> My suggestion was to rename the top-level package and keep the `aiida-core` output package but move the package's build options and requirements from the top-level the corresponding sub-package

Ok, what would be the implications of this?
Say, we rename the top-level package to `aiida` - can people then do `conda install -c conda-forge aiida` and get both outputs? Or is this just a "placeholder"?

And does this mean we should rename the feedstock?

**Comment by ltalirz** [comment]
Pinging @astamminger here - I've already updated the package to 2.0 but this might still be a good time to make the changes you proposed. A PR would be very welcome!

**Comment by ltalirz** [comment]
Cheers!
