### ISSUE TITLE
Why aiida-core==1.0.0b1 for python 3.7

### ISSUE THREAD

**Issue by astamminger** [conda-forge/aiida-core-feedstock#6]
Hi @ltalirz ,

a quick question for you: I just saw that there is an aiida-core=1.0.0b1 package available for python 3.7. However, the aiida-core package depends on circus==0.15.0 which is only available for python<=3.6 (I wonder how this even managed to build?)

**Comment by ltalirz** [comment]
> I wonder how this even managed to build?

That is a good question. I don't see the installation of the packages anywhere in the python3.7 build
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=22406

I guess, the right thing to do would be to bump the build number and skip for python 3.7 version.
Can you try?

**Comment by astamminger** [comment]
Yep, I was wondering about that too. Opened #7 to skip the build for 3.7.
One more thing: I also do not see any tests being executed for the aiida-core package, although there are imports and verdi commands defined. I'll checkout the tests of my pull request. If they are skipped there as well I'll have a look and try to find out what's the issue there.

**Comment by astamminger** [comment]
> I wonder how this even managed to build?

I think now I know why: If a sub package has the same name as the top-package this sub package will just trigger the top package build and -that's my guess- ignores what is defined in the outputs section for that package (This somehow has changed from conda 3.15 -> 3.17 ... I tested locally and everything worked just fine for the original recipe when i used conda 3.15) Thus, lacking the test section in the top package build the only thing it will do is to build/install the package using pip (which we all know happily disregards any dependencies / incompatibilities)

**Comment by ltalirz** [comment]
> lacking the test section in the top package build the only thing it will do is to build/install the package using pip

Interesting, so if you don't specify tests, then conda disregards the dependencies specified in `run`?

**Comment by astamminger** [comment]
Yes, it seems like this is what happens. Could also be a bug in conda-build for recipes with sub-packages in place (As I said, everything worked just fine with conda-build-3.15 and things started to get weird after upgrading to conda-build-3.17)

**Comment by ltalirz** [comment]
I see. So, the take home messages are:

 * make sure add tests for every recipe, otherwise dependencies may not be checked
 * For the special case of having a top-leve package and an `output` of the same name, keep tests at the top level (for the moment)
